---
- hosts: huawei
  vars:
  remote_user: root
  tasks:
  # - name: cd wenjuandiaocha
  #   command: cd ~/wenjuandiaocha
  - name: stop egg service
    command: npm run stop
    args:
      chdir: ~/wenjuandiaocha/apps/backend
  - name: update code
    command: git pull
    args:
      chdir: ~/wenjuandiaocha/apps/backend
  - name: start egg service
    command: npm run start
    args:
      chdir: ~/wenjuandiaocha/apps/backend
  handlers: